In [1]:
import requests
import pandas as pd
url = 'https://api.themoviedb.org/3/movie/popular'

headers = # Obtain personal API key from themoviedb.org database to gain access the their database, paste than information in a {}

#DO NOT SHARE THAT KEY WITH ANYONE AND MAKE SURE TO REMOVE IT HERE LIKE I DID ONCE YOU HAVE CLEANED YOUR DATA!

responce = requests.get(url,headers=headers)

data = responce.json()

print(data)

{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg', 'genre_ids': [878, 28, 12], 'id': 969681, 'title': 'Spider-Man: Brand New Day', 'original_language': 'en', 'original_title': 'Spider-Man: Brand New Day', 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.", 'popularity': 690.8873, 'poster_path': '/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg', 'release_date': '2026-07-29', 'softcore': False, 'video': False, 'vote_average': 7.847, 'vote_count': 2730}, {'adult': False, 'backdrop_path': '/7GOW6jod9lLurW5utokAatxg7ql.jpg', 'genre_ids': [35, 12, 10751], 'id': 1204680, 'title': 'Coyote vs. Acme', 'original_language': 'en', 'original_title': 'Coyote vs. Acme', 'overview': 'After Acme products fail him one too many times in his dogged pursuit of the Roadrunner, Wile E. Coyote decides to hire a billboard lawyer to sue the Acme Corporation.', 'popularity': 539.5072, 'poster_path': '/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg', 'release_date': '2026-08-20', 'softcore': False, 'video': False, 'vote_average': 7.539, 'vote_count': 427}, {'adult': False, 'backdrop_path': '/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg', 'genre_ids': [28, 27, 878], 'id': 1375646, 'title': 'Colony', 'original_language': 'ko', 'original_title': '군체', 'overview': 'Professor Se-jeong is thrust into a bloody nightmare when a rapidly mutating virus is released during a biotech conference causing authorities to seal the facility. Trapped inside with no escape, Se-jeong along with a small group of survivors must fight to stay alive while the infected undergo horrific transformations.', 'popularity': 401.4199, 'poster_path': '/tN799oUR0f1gUKDYdMNrDaY7I51.jpg', 'release_date': '2026-05-21', 'softcore': False, 'video': False, 'vote_average': 8.083, 'vote_count': 805}, {'adult': False, 'backdrop_path': '/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg', 'genre_ids': [12, 28, 14], 'id': 1368337, 'title': 'The Odyssey', 'original_language': 'en', 'original_title': 'The Odyssey', 'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.', 'popularity': 383.2533, 'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg', 'release_date': '2026-07-15', 'softcore': False, 'video': False, 'vote_average': 8.011, 'vote_count': 3750}, {'adult': False, 'backdrop_path': '/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg', 'genre_ids': [878, 9648, 53], 'id': 1101383, 'title': 'The End of Oak Street', 'original_language': 'en', 'original_title': 'The End of Oak Street', 'overview': 'After a mysterious cosmic event rips Oak Street from suburbia and transports their neighborhood to someplace unknown, the Platt family soon discovers that their very survival depends on them sticking together as they navigate their now unrecognizable surroundings.', 'popularity': 414.9533, 'poster_path': '/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg', 'release_date': '2026-08-12', 'softcore': False, 'video': False, 'vote_average': 6.879, 'vote_count': 968}, {'adult': False, 'backdrop_path': '/iRIhPqqoUHiFBxn8oYf3gCQnaKk.jpg', 'genre_ids': [28, 53], 'id': 1294189, 'title': 'The Mongoose', 'original_language': 'en', 'original_title': 'The Mongoose', 'overview': 'A falsely accused war hero with nothing to lose leads police on an epic televised cross-country car chase, helped by members of his former Special Forces Army battalion and closely monitored by a fascinated public rooting for his safe getaway.', 'popularity': 314.2254, 'poster_path': '/eSS5mvSG84UUuvtbHel5Yu3Wik4.jpg', 'release_date': '2026-10-29', 'softcore': False, 'video': False, 'vote_average': 0.0, 'vote_count': 0}, {'adult': False, 'backdrop_path': '/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg', 'genre_ids': [28, 53], 'id': 1288445, 'title': 'Mutiny', 'original_language': 'en', 'original_title': 'Mutiny', 'overview': "After witnessing his billionaire boss' murder and being framed for the crime, Cole Reed boards a cargo ship on a one-man crusade to avenge his boss' death only to discover an international conspiracy.", 'popularity': 280.2298, 'poster_path': '/pu2VxGlpGwffOx292w18b1tv96j.jpg', 'release_date': '2026-08-19', 'softcore': False, 'video': False, 'vote_average': 6.43, 'vote_count': 408}, {'adult': False, 'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg', 'genre_ids': [10751, 14, 35, 12], 'id': 1108427, 'title': 'Moana', 'original_language': 'en', 'original_title': 'Moana', 'overview': "Teenage Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with infamous demigod Maui on an unforgettable journey to restore prosperity to her people.", 'popularity': 255.7324, 'poster_path': '/gaet1xQ2nxrG0V1Ep9T20ZMNEIC.jpg', 'release_date': '2026-07-08', 'softcore': False, 'video': False, 'vote_average': 7.3, 'vote_count': 662}, {'adult': False, 'backdrop_path': '/i65y7cMae36K0giN0GRaMjAHUru.jpg', 'genre_ids': [10749, 53], 'id': 1440098, 'title': 'Drawn Together', 'original_language': 'es', 'original_title': 'Enfrentados: Marfil', 'overview': 'Marfil, daughter of a powerful Spanish businessman, sees her life in New York turned upside down when she is kidnapped and released without explanation. Her father hires Sebastian Moore as bodyguard and, forced to spend every minute together, an inevitable attraction ignites in a world where nothing is as it seems.', 'popularity': 217.9092, 'poster_path': '/6rpvddXbaQPOi0fB2HKWbZ3uUSg.jpg', 'release_date': '2026-09-09', 'softcore': False, 'video': False, 'vote_average': 6.676, 'vote_count': 85}, {'adult': False, 'backdrop_path': '/yjK3ardrgdS8suZG8KMU82Q7U38.jpg', 'genre_ids': [10749], 'id': 1285366, 'title': 'Shape of My Heart', 'original_language': 'ja', 'original_title': '愛のぬくもり', 'overview': 'A romance about a man and a woman who, due to an unexpected event, end up switching bodies. Despite coming from completely different backgrounds and environments, the two try to overcome the various difficulties that arise from their body swap.', 'popularity': 174.0468, 'poster_path': '/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg', 'release_date': '2024-07-06', 'softcore': False, 'video': False, 'vote_average': 5.688, 'vote_count': 8}, {'adult': False, 'backdrop_path': '/wVg11RahrRfghgqViuoJgcJL1iM.jpg', 'genre_ids': [35], 'id': 264980, 'title': 'Loves of a French Pussycat', 'original_language': 'de', 'original_title': 'Das Mädchen mit der heißen Masche', 'overview': "Rolf, a sex-advice columnist and a lecher, has affairs with numerous women, but never a permanent relationship. Suzanne, one of his ex-lovers, offers to bet that no woman can get Rolf to propose marriage, a bet her girlfriend Andrea eagerly accepts. But there's a catch: To win the bet, Andrea must get the womanizing Rolf to commit to marriage without first going to bed with him.", 'popularity': 268.5326, 'poster_path': '/1WGq9cMuj09tnTJ5wdkINOJff04.jpg', 'release_date': '1972-03-09', 'softcore': False, 'video': False, 'vote_average': 4.2, 'vote_count': 9}, {'adult': False, 'backdrop_path': '/1CIaRYKf3zg2Xyce1CSfCMg2Vfw.jpg', 'genre_ids': [27, 878], 'id': 1423191, 'title': 'Resident Evil', 'original_language': 'en', 'original_title': 'Resident Evil', 'overview': 'Medical courier Bryan unwittingly finds himself fighting for survival as one fateful, horrifying night collapses around him in chaos.', 'popularity': 169.2206, 'poster_path': '/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg', 'release_date': '2026-09-16', 'softcore': False, 'video': False, 'vote_average': 8.1, 'vote_count': 23}, {'adult': False, 'backdrop_path': '/akJghVpe8jwWXEA5aWRNhJWozGL.jpg', 'genre_ids': [35], 'id': 30723, 'title': 'Cavegirl', 'original_language': 'en', 'original_title': 'Cavegirl', 'overview': 'On a class excursion to a cave with stone age paintings the clumsy Rex gets lost. A mysterious crystal opens a gateway in time and sets him back to the stone ages, where he meets a group of prehistoric fellows and the gorgeous Eba. While teaching her English and doing some pseudo-research on her fellows, his main goal is to get her sleeping with him. However the curiosity of the clan chief disturbs his attempts.', 'popularity': 202.1662, 'poster_path': '/kONbgktPKsm3EMj3MiES0IP8BRr.jpg', 'release_date': '1985-05-01', 'softcore': False, 'video': False, 'vote_average': 3.923, 'vote_count': 26}, {'adult': False, 'backdrop_path': '/g7Ccid5kuD7A8hXWlsQiNfwOxaD.jpg', 'genre_ids': [28, 35], 'id': 1137844, 'title': 'Mayday', 'original_language': 'en', 'original_title': 'Mayday', 'overview': 'When a U.S. Navy pilot on a top-secret mission during the Cold War gets trapped behind enemy lines, his only chance at survival is to form an alliance with an eccentric ex-KGB agent.', 'popularity': 151.1766, 'poster_path': '/hVXjX1jLZ1ljFSNGXpjJfbTUOa7.jpg', 'release_date': '2026-09-03', 'softcore': False, 'video': False, 'vote_average': 7.982, 'vote_count': 645}, {'adult': False, 'backdrop_path': '/jzBWExXacS33rMQ2zLBrqIVweyG.jpg', 'genre_ids': [53, 28], 'id': 1386315, 'title': 'The Runner', 'original_language': 'en', 'original_title': 'The Runner', 'overview': 'Maia Marten, a brilliant London lawyer, has her life shattered by a single call on her morning run: her son has been taken. To get him back, she must keep running, obey every ruthless command, and trust no one-each second a test of how far a mother will go to save her child.', 'popularity': 167.9176, 'poster_path': '/uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg', 'release_date': '2026-09-03', 'softcore': False, 'video': False, 'vote_average': 6.77, 'vote_count': 498}, {'adult': False, 'backdrop_path': '/tK3QdOOrX4qEkmSlvrmc8cK7iOU.jpg', 'genre_ids': [27, 35, 53], 'id': 1393326, 'title': 'Ghost in the Cell', 'original_language': 'id', 'original_title': 'Hantu Dalam Sel', 'overview': 'In a notorious prison, an invisible force begins killing inmates brutally, compelling enemy gangs and corrupt guards to work together as they try to survive the mounting bloodshed.', 'popularity': 151.2661, 'poster_path': '/zxcMdx0w5Zmg8yZuuiS7CJ8vOea.jpg', 'release_date': '2026-04-16', 'softcore': False, 'video': False, 'vote_average': 7.214, 'vote_count': 63}, {'adult': False, 'backdrop_path': '/sbkkAtymJaH5UzExiK974uPzCY4.jpg', 'genre_ids': [28, 53], 'id': 1482547, 'title': 'Zip Wire', 'original_language': 'en', 'original_title': 'Zip Wire', 'overview': "When her ground-breaking pharmaceutical discovery is stolen and partner murdered, researcher Amy must face her fear of heights to escape nefarious attackers, with the only path to salvation being a treacherous aerial runway. To outsmart the mysterious hostiles, she has to summon every ounce of courage to protect the world-changing scientific discovery — and herself — before it's too late.", 'popularity': 174.3249, 'poster_path': '/cO7J0XSVKPlAjUCMWC7DVBn1Py2.jpg', 'release_date': '2026-08-31', 'softcore': False, 'video': False, 'vote_average': 7.545, 'vote_count': 11}, {'adult': False, 'backdrop_path': '/nfNaAiiILjYRc2CKkId1ZfPTtlh.jpg', 'genre_ids': [18, 10749, 35], 'id': 1408162, 'title': 'Vishwanath & Sons', 'original_language': 'ta', 'original_title': 'விஸ்வநாத் & சன்ஸ்', 'overview': 'A celebrated Olympian shooter travels to America looking for a donor to help his sick child — but unexpected romance complicates his search.', 'popularity': 155.0121, 'poster_path': '/mLsvCffzpxxDwC7yVLJSLLjgzoq.jpg', 'release_date': '2026-08-14', 'softcore': False, 'video': False, 'vote_average': 7.217, 'vote_count': 23}, {'adult': False, 'backdrop_path': '/qjTqY5coNiz6sVtPng40IzltsoN.jpg', 'genre_ids': [16, 10751, 35, 12], 'id': 1084244, 'title': 'Toy Story 5', 'original_language': 'en', 'original_title': 'Toy Story 5', 'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.", 'popularity': 146.5064, 'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg', 'release_date': '2026-06-17', 'softcore': False, 'video': False, 'vote_average': 8.354, 'vote_count': 2171}, {'adult': False, 'backdrop_path': '/tBZMwg5oCJn8P0pStfuOMhhSQD3.jpg', 'genre_ids': [10770, 10751, 28], 'id': 1506560, 'title': 'Clash of the Thundermans', 'original_language': 'en', 'original_title': 'Clash of the Thundermans', 'overview': 'When Chloe develops a destructive new superpower, the Hero League orders her to an elite boarding school for superheroes to learn control of her abilities. Faced with the prospect of sending Chloe away for years, the Thundermans split apart, with Phoebe, Barb and Billy taking her into hiding. Max, Hank, and Nora track their rogue family members, until the two factions face off against each other in a full-on battle for the Thundermans’ future.', 'popularity': 127.2023, 'poster_path': '/16oqRrWVzQm6qdGfBxvziZ2UiMT.jpg', 'release_date': '2026-09-03', 'softcore': False, 'video': False, 'vote_average': 6.857, 'vote_count': 56}], 'total_pages': 1001, 'total_results': 20001}

In [2]:
movies = data['results']
df = pd.DataFrame(movies)

In [3]:
df = df.drop(columns=['adult','backdrop_path', 'original_language', 'poster_path','softcore', 'overview', 'video','id'], axis=1)

In [4]:
all_movies = []
#Originally used range (1,11) to test if psudeo code worked before collecting the maximum amount of pages allowed by the TMBD
# DO NOT run code to print 500 pages of returned pages. ADJUST THE RANGE FIRST, unless you want to wait for the maximum return pages to load.

for page in range(1, 501):

    params = {
        "page": page
    }

    response = requests.get(
        url,
        headers=headers,
        params=params
    )

    data = response.json()
#code down below made to confirm pages within range were successfully returned
    
    #print("Requested page:", page)
    #print("TMDb returned page:", data.keys())

    all_movies.extend(movies)

In [5]:
df = pd.DataFrame(all_movies)
df.shape

(10000, 15)

In [6]:
df = df.drop(columns=['adult','backdrop_path', 'original_language', 'poster_path','softcore', 'overview', 'video','id'], axis=1)
df.head(10)

,genre_ids,title,original_title,popularity,release_date,vote_average,vote_count
0,"[878, 28, 12]",Spider-Man: Brand New Day,Spider-Man: Brand New Day,690.8873,2026-07-29,7.847,2730
1,"[35, 12, 10751]",Coyote vs. Acme,Coyote vs. Acme,539.5072,2026-08-20,7.539,427
2,"[28, 27, 878]",Colony,군체,401.4199,2026-05-21,8.083,805
3,"[12, 28, 14]",The Odyssey,The Odyssey,383.2533,2026-07-15,8.011,3750
4,"[878, 9648, 53]",The End of Oak Street,The End of Oak Street,414.9533,2026-08-12,6.879,968
5,"[28, 53]",The Mongoose,The Mongoose,314.2254,2026-10-29,0.000,0
6,"[28, 53]",Mutiny,Mutiny,280.2298,2026-08-19,6.430,408
7,"[10751, 14, 35, 12]",Moana,Moana,255.7324,2026-07-08,7.300,662
8,"[10749, 53]",Drawn Together,Enfrentados: Marfil,217.9092,2026-09-09,6.676,85
9,[10749],Shape of My Heart,愛のぬくもり,174.0468,2024-07-06,5.688,8

In [7]:
genre_url = 'https://api.themoviedb.org/3/genre/movie/list'
genre_responce = requests.get(genre_url, headers=headers)
genre_data = genre_responce.json()
genre_data

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [8]:
genre_dict = {genre['id']: genre['name']
              for genre in genre_data['genres']
             }
genre_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [9]:
def get_genre_names(genre_ids):
    return [genre_dict[genre_id] for genre_id in genre_ids]

df['genres'] = df['genre_ids'].apply(get_genre_names)
df

,genre_ids,title,original_title,popularity,release_date,vote_average,vote_count,genres
0,"[878, 28, 12]",Spider-Man: Brand New Day,Spider-Man: Brand New Day,690.8873,2026-07-29,7.847,2730,"[Science Fiction, Action, Adventure]"
1,"[35, 12, 10751]",Coyote vs. Acme,Coyote vs. Acme,539.5072,2026-08-20,7.539,427,"[Comedy, Adventure, Family]"
2,"[28, 27, 878]",Colony,군체,401.4199,2026-05-21,8.083,805,"[Action, Horror, Science Fiction]"
3,"[12, 28, 14]",The Odyssey,The Odyssey,383.2533,2026-07-15,8.011,3750,"[Adventure, Action, Fantasy]"
4,"[878, 9648, 53]",The End of Oak Street,The End of Oak Street,414.9533,2026-08-12,6.879,968,"[Science Fiction, Mystery, Thriller]"
...,...,...,...,...,...,...,...,...
9995,"[27, 35, 53]",Ghost in the Cell,Hantu Dalam Sel,151.2661,2026-04-16,7.214,63,"[Horror, Comedy, Thriller]"
9996,"[28, 53]",Zip Wire,Zip Wire,174.3249,2026-08-31,7.545,11,"[Action, Thriller]"
9997,"[18, 10749, 35]",Vishwanath & Sons,விஸ்வநாத் & சன்ஸ்,155.0121,2026-08-14,7.217,23,"[Drama, Romance, Comedy]"
9998,"[16, 10751, 35, 12]",Toy Story 5,Toy Story 5,146.5064,2026-06-17,8.354,2171,"[Animation, Family, Comedy, Adventure]"
9999,"[10770, 10751, 28]",Clash of the Thundermans,Clash of the Thundermans,127.2023,2026-09-03,6.857,56,"[TV Movie, Family, Action]"

In [10]:
df['release_date'] = pd.to_datetime(df['release_date'])
df['year'] = df['release_date'].dt.year

In [11]:
#used method explode so I can group generes later

genre_df = df.explode("genres")

genre_df.head()

,genre_ids,title,original_title,popularity,release_date,vote_average,vote_count,genres,year
0,"[878, 28, 12]",Spider-Man: Brand New Day,Spider-Man: Brand New Day,690.8873,2026-07-29,7.847,2730,Science Fiction,2026
0,"[878, 28, 12]",Spider-Man: Brand New Day,Spider-Man: Brand New Day,690.8873,2026-07-29,7.847,2730,Action,2026
0,"[878, 28, 12]",Spider-Man: Brand New Day,Spider-Man: Brand New Day,690.8873,2026-07-29,7.847,2730,Adventure,2026
1,"[35, 12, 10751]",Coyote vs. Acme,Coyote vs. Acme,539.5072,2026-08-20,7.539,427,Comedy,2026
1,"[35, 12, 10751]",Coyote vs. Acme,Coyote vs. Acme,539.5072,2026-08-20,7.539,427,Adventure,2026

In [18]:
genre_df = genre_df.rename(columns={'genres':'genre'})
genre_df = genre_df[['genre_ids','title','year','genre','vote_average','vote_count','popularity']]
genre_df = genre_df.reset_index(drop=True)
genre_df

,genre_ids,title,year,genre,vote_average,vote_count,popularity
0,"[878, 28, 12]",Spider-Man: Brand New Day,2026,Science Fiction,7.847,2730,690.8873
1,"[878, 28, 12]",Spider-Man: Brand New Day,2026,Action,7.847,2730,690.8873
2,"[878, 28, 12]",Spider-Man: Brand New Day,2026,Adventure,7.847,2730,690.8873
3,"[35, 12, 10751]",Coyote vs. Acme,2026,Comedy,7.539,427,539.5072
4,"[35, 12, 10751]",Coyote vs. Acme,2026,Adventure,7.539,427,539.5072
...,...,...,...,...,...,...,...
24495,"[16, 10751, 35, 12]",Toy Story 5,2026,Comedy,8.354,2171,146.5064
24496,"[16, 10751, 35, 12]",Toy Story 5,2026,Adventure,8.354,2171,146.5064
24497,"[10770, 10751, 28]",Clash of the Thundermans,2026,TV Movie,6.857,56,127.2023
24498,"[10770, 10751, 28]",Clash of the Thundermans,2026,Family,6.857,56,127.2023
24499,"[10770, 10751, 28]",Clash of the Thundermans,2026,Action,6.857,56,127.2023

In [19]:
genre_df.to_csv('tbmd_movies.csv',index = False)